print('>> Running assignment 2 scripts')
exec(open('exercise_1.py').read())
exec(open('exercise_2.py').read())
exec(open('exercise_3.py').read())
exec(open('exercise_4.py').read())
exec(open('exercise_5.py').read())
exec(open('exercise_6.py').read())
print('\n>> Done running assignment 2 scripts!\n')
